config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/photos',   to: 'static_pages#photos'
  get  '/raceInfo',   to: 'static_pages#raceInfo'
  get  '/success',   to: 'static_pages#success'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! } 
  validates :name,  presence: true, length: { maximum: 50 }
	 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },	
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
	
	def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
# Log the user in and redirect to the user's show page.
    else
      # Create an error message.
       flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
   log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def photos
  end

  def raceInfo
  end

  def help
  end

  def about
  end

  def success
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy 
 def index
  @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    
  end
 def edit
    @user = User.find(params[:id])
  end 
  def new
  @user = User.new
  end
 
 def create
     @user = User.new(user_params)
    if @user.save
     log_in @user
     flash[:success] = "Thank you for doing your part!!!"
     redirect_to @user
      # Handle a successful save.
    else
      render 'new'
    end
  end
 def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

 def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end

def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end


def correct_user
      @user = User.find(params[:id])
       redirect_to(root_url) unless current_user?(@user)
    end

 def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = 'Fungus Among Us')
    if page_title.empty?
      base_title = "Among Us is Fungus"
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.delish.com/food-news/a43306/bananas-extinct-fungal-disease/">Fungus Among Us
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://www.newsweek.com/worlds-bananas-are-clones-and-they-are-imminent-danger-publish-monday-5am-1321787">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Fungus Among Us", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Photos", photos_path %></li>
        <li><%= link_to "RaceInfo", raceInfo_path %></li>
	<% if logged_in? %>
	<li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<rails_default class = "rails_default">
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</rails_default>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
  <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/5kinfo.html.erb
<% provide(:title, '5kInfo') %>
<h1>InFormation</h1>
<p>
 The race starts from the Atlantic Boat and Marine (2204 Folly Road) on June 22, 2019 and finishes at the Folly Beach County Park. Rgistration begins at 6:30 am and the race will begin at 8:00 am
 Admissions are $25 per person And will be paid at event registration. 
</p>
<img alt="Fungus Among Us" src="/assets/route.png" />

app/views/static_pages/Photos.html.erb
<h1>StaticPages#Photos</h1>
<p>Find me in app/views/static_pages/Photos.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
    <h1>About Us</h1>
    <p>
      The <a href="https://www.newsweek.com/worlds-bananas-are-clones-and-they-are-imminent-danger-publish-monday-5am-1321787"><em>Fungus Among Us</em></a> is a
      movement that is trying to bring attention to the fact that OUR BANANAS ARE UNDER ATTACK!!!
    </p>
    <p>
    In recent years the overconsumption of bananas have caused modern science to do the impossible; They have cloned our bananas.Now this would be fine, but modern science can’t do what nature has perfected and our ‘artificial’ bananas have been compromised by a fungus called Fusarium oxysporum cubense. This Fungus infects the plants’ root and vascular system, unable to transport water and nutrients, the banana trees wilt and die. Our Organization is a ‘bunch’ of banana loving fanatics and won’t be able to live without bananas, So please join our cause and help us defeat this fungus and walk for something that really matters, avoiding a bananaless planet
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>
<br>
<hr class="bigHr">
<br>
<h4>
<p>Call Us: &nbsp &nbsp 1-800-867-5309<br><br>
E-Mail:&nbsp &nbsp FungusAmongUs@AOL.net
</p>
<br>
<br>
<div class="container">
  <form action="action_page.php">

    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">
    <br>
    <br>
    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">
    <br>
    <br>
    <br>
    <br>
    
    <table><tr><td><label for="subject">Message &nbsp &nbsp &nbsp &nbsp</label></td></tr>
    <tr><td><textarea id="subject" name="subject" placeholder="Write something.." style="height: 260px; width:1060px">
    </textarea></td></tr>
    </table>
    
    
<br>
    
    <%= link_to "Give Feedback", success_path, class: "btn btn-default" %>

  </form>
</div>
</h4>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Help</h1>
    <p>
     If you have any questions or comments please see the contact us page Let us know!
    </p>
  

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Join us for an exhilarating 5K race on June 22nd, 2019!</h1>

  <h2>
    Join us for an exhilarating 5K race on June 22nd, 2019! The race will be hosted on James Island going towards Folly Beach. All proceeds will go towards the non-profit organization, Fungus Among Us (FAU). If you wish to register, please hit the button below and fill out the form before June 20th. Get ready to race to the finish!
  </h2>
 <%= link_to "Sign Up Now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/photos.html.erb
<% provide(:title, "photos") %>
    <h1>Check Out Our Community</h1>

    
<img alt="Fungus Among Us" src="/assets/pic1.png" />    

<img alt="Fungus Among Us" src="/assets/pic2.png" />

<img alt="Fungus Among Us" src="/assets/pic3.png" />

<img alt="Fungus Among Us" src="/assets/pic4.png" />

<img alt="Fungus Among Us" src="/assets/pic5.png" />

<img alt="Fungus Among Us" src="/assets/pic6.png" />

<img alt="Fungus Among Us" src="/assets/pic7.png" />

<img alt="Fungus Among Us" src="/assets/pic8.png" />

app/views/static_pages/raceInfo.html.erb
<% provide(:title, 'RaceInfo') %>
<h1>Information</h1>
<p>
 The race starts at 121 E Arctic Ave on June 22, 2019.<br><br>
 Registration begins at 6:30 am and the race will begin at 8:00 am, Awards and Lunch to follow!!  Admissions are $25 per person and will be paid at event.
</p>
<img alt="Fungus Among Us" src="/assets/route.png" />

app/views/static_pages/success.html.erb
<% provide(:title, "Success") %>

<h3>Thank you for your concern!
<br>We will get back to you as soon as possible.
</h3>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
	    <%= render 'shared/error_messages' %>
	  
	    <%= f.label :team %>
      <%= f.text_field :team, class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
	    <%= f.email_field :email, class: 'form-control' %>
	  
	    <%= f.label :age %>
      <%= f.number_field :age, class: 'form-control' %>
    
      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Create User Account") %>
<% provide(:button_text, 'Register for the Race') %>
<h1>Create User Account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :team, "Team Name" %>
      <%= f.text_field :team, class: 'form-control' %>
    
      <%= f.label :name, "Your Name" %>
      <%= f.text_field :name, class: 'form-control' %>
    
      <%= f.label :email, "Email Address" %>
      <%= f.email_field :email, class: 'form-control' %>
    
      <%= f.label :age, "Your Age" %>
      <%= f.number_field :age, class: 'form-control' %>
    
      <%= f.label :phone, "Phone Number" %>
      <%= f.telephone_field :phone, class: 'form-control' %>
    
      <%= f.label :password, "Password" %>
      <%= f.password_field :password, class: 'form-control' %>
    
      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
    <br>
    <p>Registered runner? <%= link_to "Log in to your account!", login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name + " (" + @user.email + ")") %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
      <h5>
        <%= @user.email %>
      </h5>
    </section>
  </aside>
</div>

<% if current_user?(@user) %>
  <h1>Fungus Among Us Run</h1>
    <div class="container-fluid">
      <div class="row">
          <div class="col-xs-8">
              <%= yield %>
              
              <p class="textarea">
              

              <% if current_user.admin? %>
                Welcome <%= @user.name %> (Administrator)
              <% else %>
                Welcome <%= @user.name %>!!!
              <% end %>

              <h1>Schedule For June 22, 2019</h1>

              6:30 am – Registration for race begins<br>
              8:00 am – Race Starts<br>
              12:00 pm – The end of the Race "tentative"<br>
              12:30 pm – Award Ceremony and complementary lunch<br>
             
  <br><br>
              
              </p>
          </div>
          <div class="col-xs-4">
              
                                    
              
          </div>
      </div>	
  </div>

  
    <% if current_user.team? %>
X    <h1>Your Team: <%= current_user.team %></h1>
    <div class="container">     
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email Address</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <% if user.team == current_user.team %>
              <tr>
                <td><%= link_to user.name, user %></td>
                <td><%= user.email %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% end %>